apiVersion: apps/v1
kind: Deployment
metadata:
  name: icopy
spec:
  selector:
    matchLabels:
      app: icopy
  replicas: 1
  template:
    metadata:
      labels:
        app: icopy
    spec:
      containers:
        - name: icopy
          image: byxiaopeng/docker-icopy
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1m
              memory: 8Mi
            limits:
              cpu: 200m
              memory: 64Mi
